### ISSUE TITLE
Save model after run

### ISSUE THREAD

**Issue by dylanmcreynolds** [mlexchange/mlex_dlsia_segmentation_prototype#1]
We want to save the model (definition json and weights in numpy?) somewhere. Is this tiled? 

What repo would this work be done in?

**Comment by TibbersHao** [comment]
Update: currently models are saved locally under the "results" folder in a binary `.pt` file. We need some further discussion regarding this before making adjustments (was trying to make that as a topic for Monday's update but didn't have time). Maybe this would be a part for DVC to come into play.

**Comment by dylanmcreynolds** [comment]
Closed by #9
